apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      server: web
  template:
    metadata:
      labels:
        server: web
    spec:
      containers:
      - name: cpp-server-v1
        image: cpp-server:0.1.0
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-server-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    server: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

